name: App CI/CD
on:
  push: { branches: [ main ], paths: [ 'apps/ecommerce/**', '.github/workflows/app-ci.yaml' ] }
  workflow_dispatch:
    inputs:
      environment: { description: "dev, stg, prod", required: true, type: choice, options: [dev, stg, prod] }
permissions: { contents: read, id-token: write }
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets[format('AWS_ROLE_GITHUB_{0}', upper(github.event.inputs.environment || 'dev'))] }}
          aws-region: us-east-1
      - uses: aws-actions/amazon-ecr-login@v2
      - name: Build & Push (optional)
        run: |
          echo "Using public nginx image by default. Swap chart values to use ECR if desired."
      - name: Deploy
        run: |
          ENV=${{ github.event.inputs.environment || 'dev' }}
          CLUSTER=${{ secrets[format('EKS_CLUSTER_NAME_{0}', upper(ENV))] }}
          curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          aws eks update-kubeconfig --name "$CLUSTER" --region us-east-1
          helm upgrade --install ecommerce apps/ecommerce/chart -n ecommerce --create-namespace             --set ingress.host=$( [ "$ENV" = "dev" ] && echo "${{ secrets.DEV_HOST }}" || ( [ "$ENV" = "stg" ] && echo "${{ secrets.STG_HOST }}" || echo "${{ secrets.PROD_HOST }}" ) )
      - name: Helm tests
        run: helm test ecommerce -n ecommerce
