name: Terraform Plan (dev/stg/prod)
on:
  pull_request: { branches: [ main ] }
permissions: { contents: read, id-token: write }
jobs:
  plan:
    runs-on: ubuntu-latest
    strategy: { matrix: { envdir: [dev, stg, prod] } }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.7.5 }
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets[format('AWS_ROLE_GITHUB_{0}', upper(matrix.envdir))] }}
          aws-region: us-east-1
      - name: Init & Plan
        working-directory: infra/terraform/live/${{ matrix.envdir }}
        run: |
          terraform init -backend-config=backend.hcl
          terraform validate
          terraform plan -var-file=${{ matrix.envdir }}.tfvars
